# /// script
# requires-python = ">=3.12"
# dependencies = ["pillow"]
# ///
"""Rasterize printable ASCII into a compact bitmap font and emit Rust."""

from PIL import Image, ImageDraw, ImageFont

W, H = 8, 14
FIRST, LAST = 0x20, 0x7E
SIZE = 13
FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"

font = ImageFont.truetype(FONT_PATH, SIZE)

glyphs = []
for code in range(FIRST, LAST + 1):
    img = Image.new("L", (W, H), 0)
    draw = ImageDraw.Draw(img)
    draw.text((1, 0), chr(code), fill=255, font=font)
    rows = []
    for y in range(H):
        bits = 0
        for x in range(W):
            if img.getpixel((x, y)) > 96:
                bits |= 1 << (W - 1 - x)
        rows.append(bits)
    glyphs.append(rows)

out = [
    "// @generated by /tmp/opencode/genfont.py -- do not edit by hand.",
    f"pub const FONT_W: usize = {W};",
    f"pub const FONT_H: usize = {H};",
    f"pub const FONT_FIRST: u8 = 0x{FIRST:02X};",
    f"pub const FONT_LAST: u8 = 0x{LAST:02X};",
    f"pub const GLYPHS: [[u8; {H}]; {LAST - FIRST + 1}] = [",
]
for code, rows in zip(range(FIRST, LAST + 1), glyphs):
    body = ", ".join(f"0b{b:08b}" for b in rows)
    out.append(f"    [{body}], // {code:#04x} {chr(code)!r}")
out.append("];")

path = "/home/remy/offworld-nexus/screensight/src/font.rs"
with open(path, "w") as f:
    f.write("\n".join(out) + "\n")

# Render a preview of the whole set for visual inspection.
sample = Image.new("L", (W * 32 + 4, H * 4 + 8), 32)
sd = ImageDraw.Draw(sample)
for i, (code, rows) in enumerate(zip(range(FIRST, LAST + 1), glyphs)):
    ox = 2 + (i % 32) * W
    oy = 4 + (i // 32) * (H + 2)
    for y, bits in enumerate(rows):
        for x in range(W):
            if bits & (1 << (W - 1 - x)):
                sd.rectangle([ox + x, oy + y, ox + x, oy + y], fill=255)
sample.save("/tmp/opencode/font_sample.png")
print(f"wrote {path}: {len(glyphs)} glyphs; preview at /tmp/opencode/font_sample.png")
